### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by rajpat** [remojansen/TsUML#8]
### I am getting below error when I run the 
tsuml --glob ./src/**/*.ts

****C:\Users\XXXXXX\AppData\Roaming\npm\node_modules\tsuml\dist\core\io.js:71
                        var svgFileName = body.replace(".png", ".svg");
                                               ^

TypeError: Cannot read property 'replace' of undefined**
    at Request._callback** (C:\Users\927390\AppData\Roaming\npm\node_modules\tsuml\dist\core\io.js:71:48)
    at self.callback (C:\Users\927390\AppData\Roaming\npm\node_modules\tsuml\node_modules\request\request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (C:\Users\927390\AppData\Roaming\npm\node_modules\tsuml\node_modules\request\request.js:878:8)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.onConnect (C:\Users\927390\AppData\Roaming\npm\node_modules\tsuml\node_modules\tunnel-agent\index.js:168:23)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketOnData (_http_client.js:474:11)
    at Socket.emit (events.js:182:13)

**Comment by bohdanbirdie** [comment]
Consider checking other issues before creating a new one
https://github.com/remojansen/TsUML/issues/4
